#!/bin/bash

NASM_FLAGS=""
LD_FLAGS=""

if [ $(uname -s) == "Darwin" ]; then
    NASM_FLAGS="-f macho64 -F dwarf"
    LD_FLAGS="-macosx_version_min 10.14 -lSystem -e _main"
elif [ $(uname -s) == "Linux" ]; then
    NASM_FLAGS="-f elf64 -F dwarf"
    LD_FLAGS="-e main -lc -Bdynamic"
    if [ -f /lib/ld-musl-x86_64.so.1 ]; then
        LD_FLAGS+=" -dynamic-linker /lib/ld-musl-x86_64.so.1"
    fi
fi

nasm $NASM_FLAGS $1 -o test.o
ld $LD_FLAGS -o test test.o

./test
echo $?
rm ./test.o
