#!/bin/bash
/usr/local/Cellar/llvm/8.0.0_1/bin/llc ./output.ll --x86-asm-syntax=intel
flags=-lSystem #\ -lglew\ -lglfw3\ -framework\ OpenGL\ -framework\ CoreVideo\ -framework\ IOKit\ -framework\ Cocoa\ -framework\ Carbon\ -framework\ CoreFoundation
as output.s -o output.o
ld -macosx_version_min 10.14 -o output output.o -e _main $flags
if [ $? == 0 ]; then
    ./output
    echo $?
    # rm ./output
    rm ./output.o
fi
