#!/bin/bash
output=./thi
olvl=
compiler=cc
src=./src/*.c
flags=-Wall\ -Wextra\ -Wno-unused-function\ -Wno-unused-parameter\ -Werror\ -g\ -fsanitize=address\ -fno-omit-frame-pointer
std=c99

$compiler $src -std=$std $olvl $flags -o $output

if [ $? == 0 ]; then
    test_files=$
    if [ ${#test_files} == 0 ]; then
        test_files="./tests/*.thi"
    fi
    if [ $? == 0 ]; then
        if [ $(uname) = "Darwin" ]; then
            # ./runtest ./tests/test_window.thi
            # ./runtest ./tests/test_cast.thi
            # ./runtest ./tests/test_cast_explicit_f32_to_s32.thi
            # ./runtest ./tests/test_cast_explicit_f64_to_s32.thi
            # ./runtest ./tests/test_cast_explicit_f64_to_s64.thi
            # ./runtest ./tests/test_cast_explicit_f64_to_f32.thi
            # ./runtest ./tests/test_cast_explicit_s32_to_s64.thi 
            # ./runtest ./tests/test_cast_explicit_u32_to_s32.thi
            # ./runtest ./tests/test_cast_explicit_u32_to_s64.thi
            # ./runtest ./tests/test_cast_explicit_s64_to_u32.thi
            # ./runtest ./tests/test_cast_explicit_s32_to_f32.thi
            # ./runtest ./tests/test_cast_explicit_s32_to_f64.thi
            # ./runtest ./tests/test_basic_setup.thi
            # ./runtest ./tests/test_sizeof.thi
            # ./runtest ./tests/test_global_variable.thi
            # ./runtest ./tests/test_if.thi
            # ./runtest ./tests/test_math.thi
            # ./runtest ./tests/test_gt.thi
            # ./runtest ./tests/test_typeof.thi
            # ./runtest ./tests/test_optional_semicolon.thi
            # ./runtest ./tests/test_fib.thi
            ./runtest ./tests/test_file.thi
        elif [ $(uname) = "Linux" ]; then
            ./runtest ./tests/test_basic_setup_linux.thi
        fi
    fi
fi
