#!/bin/bash
output=./thi
olvl=-O3
compiler=cc
src=./src/main.c
flags=-DDEV=0\ -DNDEBUG\ -Wno-switch\ -Wno-pointer-sign
perfflags=-fno-rtti\ -fno-exceptions
std=c99
$compiler $src -std=$std $olvl $flags $perfflags -o $output
