#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEFAULT_INT_BYTE_SIZE 4
#define DEFAULT_FLOAT_BYTE_SIZE 4

#define X64_ASM_OSX_STACK_PADDING 16

#define DEFAULT_FUNCTION_ENTRY_LABEL_NAME ".BEGIN"
#define DEFAULT_FUNCTION_END_LABEL_NAME ".END"

#define INTERN_ARRAY_STARTING_ALLOC 10000
#define TOKEN_ARRAY_STARTING_ALLOC 10000

#endif
